fix the logic of script

diff --git a/auto-repos b/auto-repos
--- a/auto-repos
+++ b/auto-repos
@@ -6,13 +6,12 @@ get_media_status()
     media=$(df -h | tail -n 1 | awk '{print $1}' | cut -d'/' -f3)
     if [ $media != sr0 ]; then
         echo "Please check the media"
-        pid=$(ps aux | grep virtual-user | awk '{print $2}')
-        kill -9 $pid
+        exit 1
     fi
 }
 get_OS_version()
 {
-    version=$(cat /etc/redhat-release | awk '{print $4}' | cut -d'.' -f1)
+    version=$(grep -oE /etc/redhat-release | cut -d'.' -f1)
 }
 make_repo_file()
 {
@@ -163,4 +162,6 @@ enable=1" > /etc/yum.repos.d/local.repo
         yum upgrade -y
     fi
 }
+#Make sure only root can run our script
+[[ $EUID -ne 0 ]] && echo -e "Error,This script must be run as root!"
 auto_repo
